@startuml Sequence Diagram
participant FlaskApp
participant Postgres
participant RabbitMQ

User -> FlaskApp: Start Application
activate FlaskApp
FlaskApp -> FlaskApp: consume_messages()
activate RabbitMQ

FlaskApp -> RabbitMQ: connect to RabbitMQ
alt Connection Successful
    RabbitMQ -> RabbitMQ: start_consuming()
    loop While Consuming
        RabbitMQ -> RabbitMQ: callback()
        activate RabbitMQ
        RabbitMQ -> RabbitMQ: json.loads(body)
        RabbitMQ -> Postgres: connect_to_postgres()
        activate Postgres
        alt Connection Successful
            Postgres -> Postgres: Insert data into Postgres
            Postgres -> Postgres: commit()
        else Connection Failed
            RabbitMQ -> RabbitMQ: Send to dead letter exchange to be requeued
        end
        deactivate Postgres
        RabbitMQ -> RabbitMQ: ack()
        RabbitMQ -> Postgres: close connection
        deactivate RabbitMQ
    end
else Connection Failed
    RabbitMQ -> RabbitMQ: time.sleep(5)
end
deactivate RabbitMQ
deactivate FlaskApp
@enduml